### ISSUE TITLE
Removes the clamp from the About Me sction in the user popout, adds a scroll to it, sets it to a set height.

### ISSUE THREAD

**Issue by Slimakoi** [NYRI4/LilyPichu#21]
**Code**
```css
/* Unclamp the About Me section, so it's not limited to just 6 lines. (normally it cuts off at 6 and adds a ...) */
.clamped-2ZePhX{
    -webkit-line-clamp: 190 !important; /*Maximum amount of characters as new lines, unset just breaks links*/
    max-height: 112px !important;
    overflow-x: hidden !important;
    overflow-y: scroll !important;
}
.clamped-2ZePhX::-webkit-scrollbar {
  width: 10px !important;
  height: 15px !important;
}
.clamped-2ZePhX::-webkit-scrollbar-track {
  border-radius: 10px !important; /*How round you want the scrollbar to be. 0 is square, 10px is round.*/
  background-color: #3B1D24 !important; /*Edit this to what color you want the track to be.*/
}

.clamped-2ZePhX::-webkit-scrollbar-thumb {
  background: #220F14 !important; /* Edit this to whatever color/colors you'd like*/
  border-radius: 10px !important; /*How round you want the scrollbar thumb to be. 0 is square, 10px is round.*/
}
```

**Preview** 
![Screenshot 2022-01-15 172304](https://user-images.githubusercontent.com/24621566/149631372-52d6a8f4-36be-4363-9366-1bce91810f68.png)

**Author** Sarahhh#6076
