### ISSUE TITLE
Probably a bug in "My Account" Settings where the Banner Color is shown

### ISSUE THREAD

**Issue by feefee2** [NYRI4/LilyPichu#27]
First im unsure if this is a bug or a feature but I think it's a bug because it doen't fit in that well visualy.

Problem:
As you see in the attached screenshot the Banner Color is shown under the My Account section in the Settings

![grafik](https://user-images.githubusercontent.com/66959765/226058483-eec02b65-3922-498d-93e1-f2d504a53704.png)

Fix:
the fix for me was adding this snipet to your lilypichu.theme.css
```css
:root .accountProfileCard-lbN7n- .bannerSVGWrapper-qc0szY .banner-2boKnS {
    background-color: var(--background-secondary-alt) !important;
}
```
