### ISSUE TITLE
no background for minimise/close/full screen buttons

### ISSUE THREAD

**Issue by yand3r3d3v** [NYRI4/LilyPichu#53]
what it looks like: 
![Discord_2pAyjwfL8G](https://github.com/NYRI4/LilyPichu/assets/53695101/21234227-7bae-444c-aaa2-b3fefd57da40)

as it should be:
![chrome_3WA1pmcydv](https://github.com/NYRI4/LilyPichu/assets/53695101/6416938a-2866-4e28-82cf-5df3370990d1)

**Comment by yand3r3d3v** [comment]
im use vencord, latest version.

**Comment by PinkSerenity** [comment]
Add this to QuickCSS:
```CSS
[class*="winButton_"] {
	background-color:var(--background-primary)
}

[class*="winButton_"]:last-child {
	border-bottom-left-radius:8px
}
```
