### ISSUE TITLE
Theme broken again 

### ISSUE THREAD

**Issue by Thedigchanelh1** [NYRI4/LilyPichu#55]
![Screenshot 2024-06-25 190052](https://github.com/NYRI4/LilyPichu/assets/84262536/1430ad06-7a9f-48a4-b937-e844305cbcd6)
![Screenshot 2024-06-25 185907](https://github.com/NYRI4/LilyPichu/assets/84262536/055f0330-90d3-4140-b7b6-bdde85abbffc)

Theme broken after todays discord update

**Comment by Thedigchanelh1** [comment]
profile scaling seems broken too

**Comment by PinkSerenity** [comment]
Temporary fix: put this in your QuickCSS:
```CSS
[class*="userPanelOuter"] {
    position: fixed !important;
    top: 220px !important;
    right: 60px !important;
    bottom: 80px !important;
    width: 320px !important;
    border-radius: var(--border-radius) !important;
    overflow: hidden !important;
}
```
> profile scaling seems broken too

Don't know what you mean by that.
