### ISSUE TITLE
Member list broken

### ISSUE THREAD

**Issue by Crepper99** [NYRI4/LilyPichu#61]
![image](https://github.com/user-attachments/assets/19fee1ed-473e-4bbc-823d-ed568992ffc2)

**Comment by PinkSerenity** [comment]
Temporary fix:
```CSS
[class*="userPanelOuter"],
main[class*="chatContent_"] + canvas + canvas + div[class*="container_"],
main[class*="chatContent_"] + canvas + canvas + div[class*="membersWrap_"],
div:has(> aside[class*="membersWrap_"]) {
    position: fixed !important;
    height: auto !important;
    top: 220px !important;
    right: 60px !important;
    bottom: 80px !important;
    width: 320px !important;
    border-radius: var(--border-radius) !important;
    overflow: hidden !important;
}
```
